server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:bjitcreater/cloud2020-config.git
          search-paths:
            - cloud2020-config
          timeout: 10000
          privateKey: |
                                   -----BEGIN RSA PRIVATE KEY-----
                                   MIIJKgIBAAKCAgEAoAX2dMbi0HlIUrtBBPeg5SY5Y/VJtX4mS0bXNfbJfAxpXYYh
                                   35eGIzZC7wO/IN0237y5UzSSoidjyMhHyVvqdi/cgfygdx/g8pDfoXXXaTz51v37
                                   gzX7Gl88gdhYQ+JEhrqW+CmkQeCWAyelaJDhCHpjwNYajOtSaUbNwfGssmVM+rJb
                                   Hxaj/6JBf/U7oyvHJ2q/dVHhun+iLV1EELoexprjeqhEL5GbbQr5hELHlKIrDr1B
                                   vzP5mZN1k2AV7gn6rTURT3sucnbah/HcTzsae9DEp0RPPcH992oT4WMwZKQtynlo
                                   maGS/5L+iAM4kVmosRThnLJ9erYZD1hPI+VsQyHQA6847ugSRBD/wywcP9At44Q/
                                   VAOPzLU93GOWuH6av0Qjs7dy7ZPyYEXo+qu1BzyQ57VslalzgrsCDqtCKtxzGKON
                                   koa/PV/wwZiYhUxphE9o/C+OqLX+kLHD8l3m3qJ77FXO8+/3bIiNJogKOdjXVrQV
                                   N7MJ3Iz8H1pzFuDHtYAKDuCKGBKxyFAyzWqzzZBOsLvTS0VbUustGbkzYxzzCKWS
                                   qsQs5UP1GtdOFWe+66tgtX7e/tnktvdffR8wUHfPAEL1b5fFWTm7YOmDk+Ou+j0U
                                   /oSjmsV0BHq52wM/aBnWk4cVCC6B7ipwOlhRyXf1UVadqv/w+431uRjOCkMCAwEA
                                   AQKCAgBK9+Apf0+dWWR/lch1Okm/cPPsF2srwujP1WVXm8FzAyGNthxCcutdrbsX
                                   3Mp67AgcM38jMvsLSqbd1q6C8DPcoLmOkDrg9CdfnG2YZ+u+Gtn1VdGx++UiysE/
                                   F4rqaqOt9tZpdqDEWCIPYlCEt3MllKkNG4EeydQ3C/uzQ7Sjcv/oZwx3eRTl2y8S
                                   cmI5JHZNyh3eKbk1tTvWQt5zc66dXsz5lsEzA+Ur5btVsi9sO7kuU43stL3XrBSm
                                   MZq0hSpSYQ02DkCJUZM5ox6SY98ZaInozwDMrwh7E9AyhFSUobHuLIjLiL2kTEpA
                                   kDm9JqL4Kw8zaQ+OIKeG39lbuMzJvN9+SqnnmpgwU98pptxQGkFUBPNYqLoZJ9E9
                                   k8J4lIdK6Y7V64NhukI8/1He/nd3uSmQdV+bj8Zdt2HKPm5HuWuyIMfn4u0dO1PD
                                   VMcoESbqdHumzFEl3P5iBN4JOC7UoImljC24RwiWcu1dXwQVO3Gj7CjF3Ktaq9pp
                                   u5fu8b0t2sdU0+FaP+1dNQT+8+28N4JD95KrW3h2uIbwOeyplFX154QnoRa2PDUO
                                   KNIUnCQGB/OWtGovHK4chHzt7KK0XNWscXuIuXMlYLcneQIfWikxkvuaLr224VIx
                                   ct2pQ4XVj4VNnD2ms7fJeKv09bZwIavmwis58iVYMhmhfVfgEQKCAQEA0I5pCUj6
                                   lLyOd3MVwh30Shhtc4D5QVoInOXE+GgHXiI6wHi0STmrrhNZecNQBmepfPMdKYit
                                   TZkFKFDzUMm5jZxjPJuuNuXG1TRnoxPw6r6qALycIXV34LTdagvlBZghg0kNuXW5
                                   FDdqtW1K/aVxznkNtQUgB3f7fIflsTXp8VLVqhZVyglL6cb2EVJv//r1drnXMMf1
                                   qkNCW0L9g+pZleMeWpAdSTiPJUSLn0VvAfaRouuLhu6hv+CtUuB7AaFboIU77NqC
                                   YSt2peHZq/mXj9h1D8FE2pKrU9e5NwSA2YsWGOTrVtQOcjQbeqpei1e0/8e9SxN/
                                   1c4rapkn1UPl2QKCAQEAxG0pACtAa/vG5GdNZwI20wGSqYiNkckGAdyYSBqvs3hH
                                   zpYmH8LU37n2VWyYSoPJUcc3n74LqrS/tjLsaK6r3AnQzhOhRJOZG32raG+Nd38M
                                   aB6vpj3K958bFeQTZX9vF6AlYFixRqbn5/RFy9Wd5WhBF/iJnwk+DB4ZAndUBsKU
                                   PoiKvmtmt9D0sd8n+KUU/WuQi7bfH1f7V5gxIRM2KR9SXQC1cSmwL+NxYN79caRp
                                   6KBmKP3zPF/lKtmfI6o2kqZdqVwaRY1YoryivvSmZw+LsAGYV9ArV+Mo/rpHYmKK
                                   gcqZ17pGxm423x7aQswOSCJvanemKbMyzB+DFuuTewKCAQEAmEpliNIxqMrHfZIc
                                   IVOePzz3L5DOclo8T9W4r2vHdYWpQULi41Wpd8PJYpCsrwCjUwp0ERAs/KzwhzAV
                                   fLjRNgcsr+U+offH6YgK5Zp6IfB4U3Fm0Ufl8cAgrn9hDWS5lBSUYQkFzS1qTnEw
                                   gWd+YzciOz0y1kFW8uiJYY3s9rt2Km2E17NSK7ONm7iG8HVhKQErkgNx8JKMsfeJ
                                   B/roz/q4/4ic2gri/GPBUNxy4wwZ7M3zZOR8WJDH/+zL5bTeI6kmyR4Gds42JYt2
                                   V446jl+Rm5+Vl8XiNachKHuxWymlSShgcVcH9Xz3U+t0fmvdT6mbIGdswcN7EKwl
                                   2iVqgQKCAQEAt8+u3oma73Hc3UAOHqbjxvFh3WP7lsEW7gcQOek/IiMcjyXS50Xb
                                   DsFm0umcWZ6Zdf2G/+VH5abfABEHSa6rBG3rB+02rIWycRdYn5JEP96ULZsJo/eP
                                   R8mL/yA/RmvJ+cHTOCXHPuZRfa4I4oY0C8lToKrjnf94IL7JiJVB/FF5iEseCrNW
                                   nAzd7tV1Aij5S2ytBxFKGnqqqX2x+9GOjUzSNlXDdPId/bJJFu2VHhNNSHNRJmr+
                                   gzD5su+TDDzsdK9aVnHp48wxdZgwc6FdVnQls77KYOJcrRHV+wk2Y8ry8iI1dLrM
                                   IERi9MhaVse9VaNjv63XwI4AqyOR+JDaoQKCAQEAttEnxck/lev3og+Xfz18QOA1
                                   KNhcp3ufe8xf+1/q86L22rhWH6Y/0GPGUSk4bsq6VIGyDWByBQnTebBmVYrwZ7Oy
                                   ajWC+eEhmjBrrzfQQOW0xkUjMz9daH98Wp5vn5RQrI9CN4cRcSBvP2BZ+2CkhTWo
                                   yJFeL2tqId2KUc7hskbxrCAYlCfqnpaqqije1VFEXe6XWdGFu52g3Yn8hdBrX4pW
                                   NquEvj+hapk5By8bOodwha84DCaiIILVlNsKVMV12h15YM+7xVvaCXjAxbfyYU3S
                                   b+Mmr6OfknaEzdRf0LbJ4InT2b1/xxaVM0NTDv8pQPwtpFJBmVs0+2Dr0Q5JrQ==
                                   -----END RSA PRIVATE KEY-----

          force-pull: true
          ignore-local-ssh-settings: true

      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露bus刷新配置的端点

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
